name: 'Cypress Tests'
on:
  push:
    branches: [main]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [main]

jobs:
  build:
    name: Cypress test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      # install a specific version of Node using
      # https://github.com/actions/setup-node
      - name: Use Node.js v12
        uses: actions/setup-node@v1
        with:
          node-version: 14

      # Restore the previous NPM modules and Cypress binary archives.
      # Any updated archives will be saved automatically after the entire
      # workflow successfully finishes.
      # See https://github.com/actions/cache
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Cache Cypress binary
        uses: actions/cache@v1
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-cypress-${{ hashFiles('**/package.json') }}
          restore-keys: |
            cypress-${{ runner.os }}-cypress-

      - name: install dependencies and verify Cypress
        env:
          # make sure every Cypress install prints minimal information
          CI: 1
        # print Cypress and OS info
        run: |
          npm install
          npx cypress verify
          npx cypress info
          npx cypress version
          npx cypress version --component package
          npx cypress version --component binary
          npx cypress version --component electron
          npx cypress version --component node

      - name: Cypress tests
        run: npm run test:ci
        env:
          REACT_APP_BSP_SECRET_KEY: ${{ secrets.SECRET_KEY }}
          REACT_APP_BSP_SHARED_KEY: ${{ secrets.SHARED_KEY }}
          REACT_APP_BSP_ORGANIZATION: ${{ secrets.ORGANIZATION }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          REACT_APP_URI: ${{ secrets.REACT_APP_URI }}
          REACT_APP_GOOGLE_MAPS_API_KEY: ${{ secrets.REACT_APP_GOOGLE_MAPS_API_KEY }}

    # steps:
    #   - name: Checkout
    #     uses: actions/checkout@v2
    #   - name: Cypress run
    #     uses: cypress-io/github-action@v2
    #     with:
    #       build: npm run build
    #       start: npm run test
